
version: '3.8'
services:
  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: digibelldb
      MYSQL_USER: digibellUser
      MYSQL_PASSWORD: DigiBell@123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

